version: '3.8'
services:
    golang-http:
        container_name: vsnippet-broken-auth-spoof-5
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:1337
